name: Deploy to dev

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch å deploye (default: gjeldende branch)'
        required: false
        default: ''

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      actions: read
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}
          fetch-depth: 0

      - name: Set up pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          run_install: false
          standalone: true

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Build and push image
        uses: nais/docker-build-push@31c3a7321909bcb20799fdf46153fec721fd9512 # v0
        id: docker-build-push
        with:
          team: dab

  deploy-dev:
    name: Deploy to dev-gcp
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}
      - name: Deploy Unleash API token to dev-gcp
        uses: nais/deploy/actions/deploy@fc3eae3edebabdf67f7592102ae16176d5ba3b5f # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/unleash-api-token-dev.yaml
      - name: Deploy to dev-gcp
        uses: nais/deploy/actions/deploy@fc3eae3edebabdf67f7592102ae16176d5ba3b5f # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/app-dev.yaml
          WORKLOAD_IMAGE: ${{ needs.build.outputs.image }}
