name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      actions: read
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Build and push image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: dab

  deploy-dev:
    name: Deploy to dev-gcp
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Unleash API token to dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/unleash-api-token-dev.yaml
      - name: Deploy to dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/app-dev.yaml
          WORKLOAD_IMAGE: ${{ needs.build.outputs.image }}

  deploy-prod:
    name: Deploy to prod-gcp
    needs: [build, deploy-dev]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Unleash API token to prod-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/unleash-api-token.yaml
      - name: Deploy to prod-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/app.yaml
          WORKLOAD_IMAGE: ${{ needs.build.outputs.image }}
